---
argument_specs:
  main:
    short_description: Manages installation of common tools for hosts.
    author: Jaime Jackson-Block
    options:
      tools_htop_version:
        type: str
        description: |-
          Version specifier of the htop package.
      tools_rsync_version:
        type: str
        description: |-
          Version specifier of the rsync package.
      tools_tmux_version:
        type: str
        description: |-
          Version specifier of the tmux package.
...
