---
- name: Main | Include package/main.yaml tasks
  ansible.builtin.include_tasks: package/main.yaml

- name: Main | Template chrony.conf file
  when: chrony_conf_src | default(None) != None
  become: true
  ansible.builtin.template:
    src: "{{ chrony_conf_src }}"
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart chrony service
...
