---
- name: Choose tasks by package manager
  with_first_found:
    - files:
        - "{{ ansible_facts.pkg_mgr }}.yaml"
        - default.yaml
      paths:
        - package
  loop_control:
    loop_var: pkg
  ansible.builtin.include_tasks: "{{ pkg }}"

- name: Template chrony.conf file
  when: chrony_conf_src | default(None) != None
  become: true
  ansible.builtin.template:
    src: "{{ chrony_conf_src }}"
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart chrony service
...
