---
- name: Package | APT | Install htop, rsync, tmux
  become: true
  ansible.builtin.apt:
    state: present
    name:
      - htop{{ tools_htop_version | default(None) }}
      - rsync{{ tools_rsync_version | default(None) }}
      - tmux{{ tools_tmux_version | default(None) }}
...
