---
- name: Run `kadmin addprinc ...` with delegated failure
  become: true
  ansible.builtin.expect:
    command: >-
      {{ krb5_principal_kadmin_command_init }}
      addprinc
      {{
        (
          '-allow_svr +requires_preauth'
          if krb5_principal_type == 'user' else
          '+allow_svr -requires_preauth -nokey'
        ) + (
          ''
          if krb5_principal_policy | length == 0 else
          (' -policy ' + krb5_principal_policy)
        )
      }}
      {{ krb5_principal_name }}
    responses: >-
      {{
        krb5_principal_kadmin_responses_init
        if krb5_principal_type == 'service' else
        (
          krb5_principal_kadmin_responses_init
          | ansible.builtin.combine({
              'Enter password for principal': krb5_principal_password,
              'Re-enter password for principal': krb5_principal_password
            })
        )
      }}
  no_log: true
  register: krb5_principal_addprinc
  changed_when: krb5_principal_addprinc.rc == 0
  failed_when: false

- name: Delegated failure for 'kadmin addprinc ...'
  when:
    - krb5_principal_addprinc.rc > 0
  ansible.builtin.fail:
    msg: "{{ krb5_principal_addprinc.stdout_lines[-1] }}"
...
