---
- name: Choose tasks by package manager
  with_first_found:
    - files:
        - "{{ ansible_facts.pkg_mgr }}.yaml"
        - default.yaml
      paths:
        - package
  loop_control:
    loop_var: pkg
  ansible.builtin.include_tasks: "{{ pkg }}"

- name: Ensure /etc/systemd/timesyncd.conf.d directory exists
  become: true
  ansible.builtin.file:
    path: /etc/systemd/timesyncd.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Template /etc/systemd/timesyncd.conf.d/00-ansible.conf
  become: true
  ansible.builtin.template:
    src: etc/systemd/timesyncd.conf.d/00-ansible.conf.j2
    dest: /etc/systemd/timesyncd.conf.d/00-ansible.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart systemd-timesyncd service
...
