---
- name: Main | Include package/main.yaml tasks
  ansible.builtin.include_tasks: package/main.yaml

- name: Main | Create /etc/systemd/timesyncd.conf.d directory
  become: true
  ansible.builtin.file:
    path: /etc/systemd/timesyncd.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Main | Template /etc/systemd/timesyncd.conf.d/00-ansible.conf
  become: true
  ansible.builtin.template:
    src: etc/systemd/timesyncd.conf.d/00-ansible.conf.j2
    dest: /etc/systemd/timesyncd.conf.d/00-ansible.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart systemd-timesyncd service
...
