---
- name: Initialize variables for Debian distribution
  ansible.builtin.set_fact:
    ca_certificates_share_dir: /usr/local/share/ca-certificates
    ca_certificates_share_ext: .crt
    ca_certificates_update_cmd: /usr/sbin/update-ca-certificates

- name: Install ca-certificates apt package
  loop:
    - name: ca-certificates
      version: "{{ ca_certificates_version }}"
  become: true
  ansible.builtin.apt:
    name: "{{ item.name }}{% if item.version != 'latest' %}{{ item.version }}{% endif %}"
    state: "{% if item.version == 'latest' %}latest{% else %}present{% endif %}"
...
