---
- name: Include distribution init tasks
  ansible.builtin.include_tasks: "init/{{ ansible_facts.distribution }}.yaml"

- name: Copy CA certificates
  loop: "{{ ca_certificates_pem | default([]) }}"
  become: true
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ ca_certificates_share_dir }}/{{ item.name }}{{ ca_certificates_share_ext }}"
    mode: "0644"
    backup: true
  notify: Update CA certificates
...
